version: '3.9'

services: 
	BDProd:
		image: postgres:latest
		restart: always
		container_name: postgresComparativo
		hostname: localhost
		environment: 
			POSTGRES_DB: medicamentos
			POSTGRES_USER: jdiaz
			POSTGRES_PASSWORD: 123456Aa
		volumes:
			- /home/jdiaz/compartida/docker/volumes/DBProd:/var/lib/postgresql/data
			- ./sql/tabla_alfabeta.sql:/docker-entrypoint-initdb.d/tabla_alfabeta.sql
			- ./sql/tabla_kairos.sql:/docker-entrypoint-initdb.d/tabla_kairos.sql
			- ./sql/datos_alfabeta.sql:/docker-entrypoint-initdb.d/datos_alfabeta.sql
			- ./sql/datos_kairos.sql:/docker-entrypoint-initdb.d/datos_kairos.sql
		ports:
			- "9091:5432"
		