-- public.alfabeta definition

-- Drop table

-- DROP TABLE public.alfabeta;

CREATE TABLE public.alfabeta (
	fecha_extraccion timestamp NOT NULL,
	troquel varchar(20) NOT NULL,
	nombre varchar(250) NULL,
	presentacion varchar(250) NULL,
	blanco varchar(10) NULL,
	ioma_normatizado varchar(1) NULL,
	ioma_internacion varchar(1) NULL,
	laboratorio varchar(100) NULL,
	controlado varchar(1) NULL,
	importado bit(1) NULL,
	tipoventa int4 NULL,
	iva bit(1) NULL,
	desc_pami int4 NULL,
	cod_lab varchar(4) NULL,
	registro varchar(10) NULL,
	baja bit(1) NULL,
	cod_barra varchar(20) NULL,
	unidades int4 NULL,
	tamano_x varchar(1) NULL,
	heladera bit(1) NULL,
	sifar varchar(1) NULL,
	pami_vivirmejor varchar(1) NULL,
	gravamen varchar(1) NULL,
	blanco2 varchar(2) NULL,
	precio numeric NULL,
	fecha timestamp NULL,
	tamano_y varchar(2) NULL,
	cod_accion varchar(5) NULL,
	cod_droga varchar(5) NULL,
	cod_forma varchar(5) NULL,
	potencia varchar(100) NULL,
	cod_unidad varchar(5) NULL,
	cod_tipounidad varchar(5) NULL,
	cod_via varchar(5) NULL,
	droga varchar(100) NULL,
	accion_farmacologica varchar(100) NULL,
	forma_farmaceutica varchar(100) NULL,
	pm numeric(12, 10) NULL,
	pm_1 numeric(12, 10) NULL,
	pm_2 numeric(12, 10) NULL,
	nne2 int4 NULL,
	codigo1 varchar(20) NULL,
	codigo2 int4 NULL,
	ppu numeric NULL,
	nne int4 NULL,
	dto1 numeric(12, 10) NULL,
	dto2 numeric(12, 10) NULL
);